// Copyright (c) 2026 devlive-community/grantforge
//
// Licensed under the MIT License. See the LICENSE file in the
// project root for full license text.

package org.devlive.grantforge.service.agent;

import org.devlive.grantforge.identity.application.SecretBox;
import org.devlive.grantforge.identity.domain.PlatformSetting;
import org.devlive.grantforge.identity.domain.PlatformSettingRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Component;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.TransactionDefinition;
import org.springframework.transaction.support.TransactionTemplate;

import java.security.GeneralSecurityException;
import java.security.KeyFactory;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.MessageDigest;
import java.security.PrivateKey;
import java.security.Signature;
import java.security.spec.PKCS8EncodedKeySpec;
import java.util.Base64;
import java.util.HexFormat;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicReference;

import static java.util.Objects.requireNonNull;

/**
 * Signs policy snapshots with Ed25519, so agents can tell they come from this server unchanged. The key pair is
 * generated once and kept in the platform settings, the private key sealed by {@link SecretBox}; every node shares it.
 */
@Component
public final class SnapshotSigner
{
    /** Where the key pair is kept. */
    static final String SETTING = "security.snapshot-signing-key";

    private static final Logger LOG = LoggerFactory.getLogger(SnapshotSigner.class);
    private static final String ALGORITHM = "Ed25519";
    private static final String FORMAT = "ed25519:";

    private final PlatformSettingRepository settings;
    private final SecretBox secrets;
    private final TransactionTemplate own;
    private final AtomicReference<Keys> keys = new AtomicReference<>();

    /**
     * Creates the signer.
     *
     * @param settings the platform settings
     * @param secrets seals the private key
     * @param transactionManager opens a transaction of its own to store a generated key pair
     */
    public SnapshotSigner(PlatformSettingRepository settings, SecretBox secrets, PlatformTransactionManager transactionManager)
    {
        this.settings = requireNonNull(settings, "settings");
        this.secrets = requireNonNull(secrets, "secrets");
        this.own = new TransactionTemplate(requireNonNull(transactionManager, "transactionManager"));
        own.setPropagationBehavior(TransactionDefinition.PROPAGATION_REQUIRES_NEW);
    }

    /**
     * Signs data.
     *
     * @param data the data
     * @return the signature, Base64
     * @throws IllegalStateException if the stored key cannot be read
     */
    public String sign(byte[] data)
    {
        try {
            Signature signature = Signature.getInstance(ALGORITHM);
            signature.initSign(keys().privateKey());
            signature.update(data);
            return Base64.getEncoder().encodeToString(signature.sign());
        }
        catch (GeneralSecurityException impossible) {
            throw new IllegalStateException("Ed25519 is not available", impossible);
        }
    }

    /**
     * Returns the public key agents check signatures with.
     *
     * @return the key
     */
    public SigningKey publicKey()
    {
        Keys current = keys();
        return new SigningKey(current.keyId(), ALGORITHM, current.publicKey());
    }

    private Keys keys()
    {
        Keys known = keys.get();
        if (known == null) {
            known = decode(stored());
            keys.compareAndSet(null, known);
        }
        return known;
    }

    private Keys decode(String value)
    {
        int split = value.indexOf(':', FORMAT.length());
        if (!value.startsWith(FORMAT) || split < 0) {
            throw new IllegalStateException("the stored snapshot signing key is not readable");
        }
        String publicKey = value.substring(FORMAT.length(), split);
        try {
            byte[] encoded = Base64.getDecoder().decode(secrets.open(value.substring(split + 1)));
            PrivateKey privateKey = KeyFactory.getInstance(ALGORITHM).generatePrivate(new PKCS8EncodedKeySpec(encoded));
            return new Keys(keyId(publicKey), publicKey, privateKey);
        }
        catch (GeneralSecurityException | IllegalArgumentException broken) {
            throw new IllegalStateException("the stored snapshot signing key is not readable", broken);
        }
    }

    /** The stored key pair, generated by the first node that needs one. */
    private String stored()
    {
        String existing = read().orElse(null);
        if (existing != null) {
            return existing;
        }
        KeyPair pair;
        try {
            pair = KeyPairGenerator.getInstance(ALGORITHM).generateKeyPair();
        }
        catch (GeneralSecurityException impossible) {
            throw new IllegalStateException("Ed25519 is not available", impossible);
        }
        Base64.Encoder base64 = Base64.getEncoder();
        String value = FORMAT + base64.encodeToString(pair.getPublic().getEncoded()) + ":"
                + secrets.seal(base64.encodeToString(pair.getPrivate().getEncoded()));
        try {
            own.executeWithoutResult(status -> settings.saveAndFlush(PlatformSetting.of(SETTING, value)));
            LOG.info("Generated the key pair policy snapshots are signed with");
            return value;
        }
        catch (DataIntegrityViolationException concurrent) {
            // Another node stored a key pair at the same moment: use that one.
            return read().orElseThrow(() -> new IllegalStateException("the stored snapshot signing key vanished", concurrent));
        }
    }

    private Optional<String> read()
    {
        return requireNonNull(own.execute(status -> settings.findBySettingKey(SETTING)
                .flatMap(setting -> Optional.ofNullable(setting.getSettingValue()))));
    }

    private static String keyId(String publicKey)
    {
        try {
            byte[] digest = MessageDigest.getInstance("SHA-256").digest(Base64.getDecoder().decode(publicKey));
            return HexFormat.of().formatHex(digest).substring(0, 16);
        }
        catch (GeneralSecurityException impossible) {
            throw new IllegalStateException("SHA-256 is not available", impossible);
        }
    }

    /** The key pair in use. */
    private record Keys(String keyId, String publicKey, PrivateKey privateKey)
    {
    }
}
