# Copyright (c) 2026 devlive-community/grantforge
#
# Licensed under the MIT License. See the LICENSE file in the
# project root for full license text.

server.port=9999
spring.datasource.url=${GRANTFORGE_DB_URL:jdbc:mysql://localhost:3306/${GRANTFORGE_DB_NAME:grantforge}?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false}
spring.datasource.username=${GRANTFORGE_DB_USER:root}
spring.datasource.password=${GRANTFORGE_DB_PASSWORD:12345678}
spring.sql.init.mode=never
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false
spring.flyway.validate-on-migrate=true
spring.flyway.validate-migration-naming=true
spring.flyway.clean-disabled=true
spring.flyway.out-of-order=false
