// Copyright (c) 2026 devlive-community/grantforge
//
// Licensed under the MIT License. See the LICENSE file in the
// project root for full license text.

import type { components } from '@/api/schema'

type Action = components['schemas']['AuditEventResponse']['action']

/** Every kind of audit event, in the order the server declares them, for the audit log's filter. */
export const auditActions = [
  'LOGIN_SUCCEEDED', 'LOGIN_FAILED', 'ACCOUNT_LOCKED', 'LOGOUT', 'SESSION_REVOKED', 'PASSWORD_CHANGED', 'TENANT_CREATED', 'TENANT_UPDATED',
  'TENANT_SUSPENDED', 'TENANT_ACTIVATED', 'ORG_UNIT_CREATED', 'ORG_UNIT_UPDATED', 'ORG_UNIT_MOVED', 'ORG_UNIT_DELETED', 'USER_CREATED',
  'USER_UPDATED', 'USER_ENABLED', 'USER_DISABLED', 'USER_LOCKED', 'USER_UNLOCKED', 'USER_PASSWORD_RESET', 'USER_DELETED',
  'USER_REGISTERED', 'GROUP_CREATED', 'GROUP_UPDATED', 'GROUP_DELETED', 'GROUP_MEMBERS_ADDED', 'GROUP_MEMBERS_REMOVED', 'POSITION_CREATED',
  'POSITION_UPDATED', 'POSITION_DELETED', 'USERS_IMPORTED', 'ORG_UNITS_IMPORTED', 'APPLICATION_CREATED', 'APPLICATION_UPDATED',
  'APPLICATION_DELETED', 'RESOURCE_CREATED', 'RESOURCE_UPDATED', 'RESOURCE_MOVED', 'RESOURCE_DELETED', 'API_CHANGES_REVIEWED',
  'RESOURCE_DEPENDENCY_ADDED', 'RESOURCE_DEPENDENCY_CHANGED', 'RESOURCE_DEPENDENCY_REMOVED', 'ROLE_CREATED', 'ROLE_UPDATED', 'ROLE_COPIED',
  'ROLE_ENABLED', 'ROLE_DISABLED', 'ROLE_DELETED', 'ROLE_ASSIGNED', 'ROLE_ASSIGNMENT_CHANGED', 'ROLE_UNASSIGNED', 'ROLE_GRANTS_CHANGED',
  'ROLE_PARENTS_CHANGED', 'PLUGIN_ENABLED', 'PLUGIN_DISABLED', 'PLUGINS_RESCANNED', 'SERVICE_CREATED', 'SERVICE_UPDATED',
  'SERVICE_DELETED', 'POLICY_CREATED', 'POLICY_UPDATED', 'POLICY_DELETED', 'AGENT_TOKEN_ISSUED', 'AGENT_TOKEN_REVOKED',
  'DATA_POLICY_CREATED', 'DATA_POLICY_UPDATED', 'DATA_POLICY_DELETED', 'FIELD_POLICIES_CHANGED', 'ACCESS_DENIED', 'CLIENT_CREATED', 'CLIENT_UPDATED',
  'CLIENT_SECRET_ROTATED', 'CLIENT_DELETED', 'OAUTH_AUTHORIZED', 'OAUTH_TOKEN_REPLAYED', 'SIGNING_KEY_ROTATED',
] as const satisfies readonly Action[]
