# Copyright (c) 2026 devlive-community/grantforge
#
# Licensed under the MIT License. See the LICENSE file in the
# project root for full license text.

name: Publish docs via GitHub Pages

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Build and deploy documentation
        run: bash script/ci/publish_docs.sh

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
